### ISSUE TITLE
Build error in FastBoot

### ISSUE THREAD

**Issue by bakerac4** [concordnow/ember-aria-tabs#169]
I tried to use this in FastBoot and saw the following build error

```
Error: Accessing `this.element` is not allowed in non-interactive environments (such as FastBoot).
    at InertRenderer.getElement (/var/folders/2l/h4z8hz2j6b50w15hblt8mvm40000gn/T/broccoli-3932BwuPWuaoG4Ab/out-1086-broccoli_persistent_filter_autoprefixer_filter/assets/@ember/-internals/glimmer/index.js:9168:1)
    at Class.get (/var/folders/2l/h4z8hz2j6b50w15hblt8mvm40000gn/T/broccoli-3932BwuPWuaoG4Ab/out-1086-broccoli_persistent_filter_autoprefixer_filter/assets/@ember/-internals/views/lib/mixins/view_support.js:136:1)
    at Class.<anonymous> (/var/folders/2l/h4z8hz2j6b50w15hblt8mvm40000gn/T/broccoli-3932BwuPWuaoG4Ab/out-1086-broccoli_persistent_filter_autoprefixer_filter/assets/addon-tree-output/ember-aria-tabs/components/aria-tab.js:80:1)
```

**Comment by arjenblokzijl** [comment]
Can confirm.

**Comment by arjenblokzijl** [comment]
Hey @thiberaw,

Do you accept any PR's? I am happy to take a look at this later on today.

**Comment by arjenblokzijl** [comment]
@thiberaw see: https://github.com/concordnow/ember-aria-tabs/pull/183

Please let me know if I need to improve someting.

**Comment by ctjhoa** [comment]
Sorry for the late reply.
We do not use fastboot in our app.
I will dig how to tackle fastboot issue and get back at you ASAP,

**Comment by thiberaw** [comment]
@arjenblokzijl So sorry to be so late in my reply ... weird times we're living in. As @ctjhoa said we'll have a look at it.
